# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0af42b3c1eb9df4702a6da3e9969af82f2c6bb177ef800973a822c88ee83e4ac20f3392afab6c7c4ae487dd53731ca2154da91118a4fd317210f2639d1ebb723

test:
  secret_key_base: cc67fb105c4eb2272b2dc08184e10b149bc8bc680d80e86cef864a693a6617d3dfb073b31ee282d5ac6a5961bfbccc74615aa3882c23eb984483ad2d31cfb313

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
